server:
  port: 8080
  servelet:
    context-path: /bootcamp

springdoc:
  swagger-ui:
    path: /bootcamp/swagger-ui.html

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://necvmlkdgbbxza:0d42f4db6f38b5f7e19969b677cb8ea619f5129317464d6136767425aa7ef9d7@ec2-23-23-128-222.compute-1.amazonaws.com:5432/d1ka9f8bn4j6bs
    username: necvmlkdgbbxza
    password: 0d42f4db6f38b5f7e19969b677cb8ea619f5129317464d6136767425aa7ef9d7
  jpa:
    show-sql: true
    database-plataform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

application:
  description: Projeto criado para o Bootcamp DIO - Santander
